### ISSUE TITLE
improve ircv3 support

### ISSUE THREAD

**Issue by examknow** [solanum-ircd/solanum#120]
Solanum is a little behind as far as IRCv3 features are concerned. It would be nice to see things like message-tags and history playback added in the future. Most of the popular modern IRCds have this and I think many users (myself included) would like to see this.

**Comment by edk0** [comment]
Thanks for the report. We're interested in those features, but we won't be focusing on them in the short term, and I think it's best that we keep the tracker focused on actionable issues. We'll bring these back when we're in a position to work on them.

**Comment by Krinkle** [comment]
Ref https://github.com/solanum-ircd/solanum/issues/157.
