### ISSUE TITLE
offer SASL when agent missing but instantly ERR_SASLFAIL

### ISSUE THREAD

**Issue by jesopo** [solanum-ircd/solanum#125]
I don't like the idea of new clients not knowing that we *support* SASL just because services is currently missing, and I think it's easier to understand as a failure to an end user than SASL just suddenly being gone.

**Comment by jesopo** [comment]
I think we'll want to get rid of this and the things that use it https://github.com/solanum-ircd/solanum/blob/2e8a889fc94313acf53c430cec1bd044850769a0/modules/m_sasl.c#L371

and change this function to not need the agent's nickname to be online https://github.com/solanum-ircd/solanum/blob/2e8a889fc94313acf53c430cec1bd044850769a0/modules/m_sasl.c#L90

and then we can rely on this to catch the agent being gone. https://github.com/solanum-ircd/solanum/blob/2e8a889fc94313acf53c430cec1bd044850769a0/modules/m_sasl.c#L165

title of this issue went for `ERR_SASLFAIL` - is `ERR_SASLABORTED` more correct?

**Comment by jesopo** [comment]
would look like

```
< :sand.cat NOTICE * :*** Looking up your hostname...
< :sand.cat NOTICE * :*** Checking Ident
< :sand.cat NOTICE * :*** Found your hostname
< :sand.cat NOTICE * :*** No Ident response
> CAP LS
< :sand.cat CAP * LS :account-notify away-notify cap-notify chghost extended-join multi-prefix sasl tls userhost-in-names
> CAP REQ sasl
< :sand.cat CAP * ACK :sasl
> AUTHENTICATE PLAIN
< :sand.cat 906 * :SASL authentication aborted
```

**Comment by edk0** [comment]
we could also consider holding sasl sessions for a certain period of time if the sasl agent goes away, restarting them if it comes back and aborting them if it doesn't.

in practice a ton of losses of sasl agent are netsplits preceded by a long ping timeout, so it'd be good to have a better experience for them, too; applying separate timeout logic to all sasl sessions might solve that
