### ISSUE TITLE
remove "name is equal to my own name" connect block error snotice

### ISSUE THREAD

**Issue by xfnw** [solanum-ircd/solanum#155]
```
-- etc/ircd.conf :Rehashing
-- irc.example.com: *** Notice -- error: "etc/ircd.conf", line 277: Ignoring connect block for irc.example.com -- name is equal to my own name.
```

this error is almost never useful, and in situations where you would have a connect block for itself, for example a shared pool of connect blocks between all servers, it can be quite annoying to see on every rehash

**Comment by examknow** [comment]
-1: I think it is useful to have this error since it could help with debugging if someone were to put the name of server in the name of the connect block by mistake. You could always use ansible or similar to generate the connect blocks and make sure that none of them are invalid.

**Comment by aaronmdjones** [comment]
Sharing the same set of connect blocks between all servers is a recipe for disaster. For example, it requires you to use the same linking password regardless of which server is initiating the connection, and it prevents you from using the vhost parameter to indicate the address to make the connection from.
