### ISSUE TITLE
/list sometimes not showing all channels

### ISSUE THREAD

**Issue by RealKindOne** [solanum-ircd/solanum#168]
```sauvin``` on ```irc.libera.chat```  discovered the bug. I can also replicate it multiple time.

It looks like ```/list``` is being downloaded and getting chopped off at random places.

This is my attempt from a connection not on any channels on this server, I stayed connected during this test.

```solanum-1.0-dev(20210520-b3d424cb). tantalum.libera.chat eIKMpSZ6 TS6ow```

Attempt 1:

https://www.dropbox.com/s/bmdhkgjdicnr2h0/list-1.txt?dl=0
https://www.dropbox.com/s/guxxljpzqp0ezml/rawlog-1.txt?dl=0

Attempt 2:

https://www.dropbox.com/s/gbg6i34s3jhxgro/list-2.txt?dl=0
https://www.dropbox.com/s/vt3fbq459q5tmqm/rawlog-2.txt?dl=0

Attempt 3:

https://www.dropbox.com/s/v2q2pa6et5y0ssp/list-3.txt?dl=0
https://www.dropbox.com/s/0bfb53et75niruj/rawlog-3.txt?dl=0

Attempt 4: 

https://www.dropbox.com/s/8hnra7h3oaxucv5/list-4.txt?dl=0
https://www.dropbox.com/s/qqoxybd1s9urgsk/rawlog-4.txt?dl=0

On each attempt the list size increases. I did not test how many times it would take to get the full /list.

Edit 1:

Correct Attempt 4 section.

**Comment by RealKindOne** [comment]
After performing a git bisect between git head and 3.5.0, this commit seems to cause the bug? 999fab778cb247ab51b9f49da828c37b1831a547

**Comment by FrostKiwi** [comment]
Depending on the client, this is issue is reported by a bunch of users, including me on the client ERC (Emacs' built in IRC client)
I get to channels listed starting with letters #D to #J

**Comment by sorear** [comment]
/list points users at netsplit.de if there are too many matches, which is problematic because the netsplit.de list also cuts off around #P, possibly due to this issue.

**Comment by aaronmdjones** [comment]
I believe the problem is caused by

https://github.com/solanum-ircd/solanum/blob/a6f63a829e22fa83a4551cb9aad3e316e7c8bb18/librb/src/radixtree.c#L486-L487

Adam suggested removing it, and this does resolve the issue for me in local testing

**Comment by aaronmdjones** [comment]
For reference, this issue cannot be reliably bisected, or a fix tested, without the following temporary patch to simulate filling the sendq

```diff
--- a/modules/m_list.c
+++ b/modules/m_list.c
@@ -472,10 +472,11 @@ static void safelist_iterate_client(struct Client *source_p)
 {
 	struct Channel *chptr;
 	rb_radixtree_iteration_state iter;
+	int itercnt = 0;
 
 	RB_RADIXTREE_FOREACH_FROM(chptr, &iter, channel_tree, source_p->localClient->safelist_data->chname)
 	{
-		if (safelist_sendq_exceeded(source_p->from))
+		if (++itercnt > 2)
 		{
 			rb_free(source_p->localClient->safelist_data->chname);
 			source_p->localClient->safelist_data->chname = rb_strdup(chptr->chname);
```

**Comment by RealKindOne** [comment]
> I believe the problem is caused by
> 
> https://github.com/solanum-ircd/solanum/blob/a6f63a829e22fa83a4551cb9aad3e316e7c8bb18/librb/src/radixtree.c#L486-L487
> 
> Adam suggested removing it, and this does resolve the issue for me in local testing

Removing those two lines also worked for me in local testing. All 11,000+on my ircd show up in /list.

**Comment by kaniini** [comment]
Try with this:

```diff
diff --git a/librb/src/radixtree.c b/librb/src/radixtree.c
index 581eba04..ed2ccb6d 100644
--- a/librb/src/radixtree.c
+++ b/librb/src/radixtree.c
@@ -639,12 +639,11 @@ rb_radixtree_foreach_start_from(rb_radixtree *dtree, rb_radixtree_iteration_stat
 
 	if (key != NULL)
 	{
-		STATE_CUR(state) = NULL;
-		STATE_NEXT(state) = rb_radixtree_elem_find(dtree, key, 1);
+		STATE_CUR(state) = rb_radixtree_elem_find(dtree, key, 1);
+		STATE_NEXT(state) = first_leaf(STATE_CUR(state));
 
-		/* make STATE_CUR point to selected item and STATE_NEXT point to
-		 * next item in the tree */
-		rb_radixtree_foreach_next(dtree, state);
+		if (STATE_CUR(state) == STATE_NEXT(state))
+			STATE_NEXT(state) = NULL;
 	}
 	else
 		rb_radixtree_foreach_start(dtree, state);
```
