### ISSUE TITLE
add solanum.chat/oper capability, message tag

### ISSUE THREAD

**Issue by edk0** [solanum-ircd/solanum#214]
should add a `@solanum.chat/opername=foo` tag to messages from an oper whose oper block is named `foo`. The `cap_realhost` extension can serve as an example. As with realhost, there will need to be a hidden version of the capability that is automatically set for opers who can see through oper hiding.

**Comment by edk0** [comment]
revision after thinking about it for a few more seconds: let's make it `@solanum.chat/oper` and include a name if we know the name.

we'll probably need two hidden caps -- one for opers who can see through oper hiding (i.e. they have `auspex:oper`), and one for all other opers. other users will never see opernames, but they would see the oper status of non-hidden opers, so we *could* add yet another hidden cap for them... but that's getting quite expensive in terms of capability bits.

**Comment by SadieCat** [comment]
FWIW if you'd be interested in taking this to IRCv3 I'd also be interested in implementing it.

**Comment by edk0** [comment]
> FWIW if you'd be interested in taking this to IRCv3 I'd also be interested in implementing it.

yeah, I don't see why not

**Comment by examknow** [comment]
We'd also need to check if the oper has `oper:hidden` when sending the tag to people who don't have `oper:auspex` even if oper hiding isn't configured server wide.

**Comment by kaniini** [comment]
We will be glad to carry this in Ophion as well.
