### ISSUE TITLE
add snomask char to show all new connection d/k/x-line rejections

### ISSUE THREAD

**Issue by jesopo** [solanum-ircd/solanum#234]
might be handy to be able to opt in to seeing things bounce off klines/dlines

**Comment by jesopo** [comment]
`notify_banned_client` isnt the right place for this at all given the aim of this is to only show when stuff fails to connect due to a d/k/x-line, but it seems there's no central handling for this, so

https://github.com/solanum-ircd/solanum/blob/d24434edb7969accf614ed82065d95c24380cab9/ircd/listener.c#L629-L635
https://github.com/solanum-ircd/solanum/blob/81531536aac9adb585c5a17b448aa0496bf68ebd/ircd/s_conf.c#L362-L368
https://github.com/solanum-ircd/solanum/blob/e62ec6f17c37a80ac871663abfccae5f93754126/ircd/s_user.c#L554-L559

**Comment by jesopo** [comment]
annoying bit about this is it'll make dlines a lot more computationally complicated when they're intended to be as close to a no-op as possible

**Comment by jillest** [comment]
> annoying bit about this is it'll make dlines a lot more computationally complicated when they're intended to be as close to a no-op as possible

Perhaps it is best to exclude dlines from this feature. Sending notices for klines and xlines is like the existing notices for dnsbl: rejectcache rate-limits them. (So rejectcache rejects should not send notices either.)
