### ISSUE TITLE
"Nick/channel is temporarily unavailable" (437) message should not be sent if you're already using that nickname

### ISSUE THREAD

**Issue by nyuszika7h** [solanum-ircd/solanum#248]
Scenario that just happened on libera:
* Got disconnected from the network due to a netsplit
* Reconnected and did `/ns regain` before ZNC's keepnick module got to it
* ZNC's keepnick module keeps trying to get the nick (arguably it is buggy too because it should see that I'm already using it)
* My server buffer is spammed with `-- nyuszika7h: Nick/channel is temporarily unavailable`, even though my current nick is already nyuszka7h

**Comment by dwfreed** [comment]
The RSFNC handler doesn't delete the nickdelay entry when changing the user's nick.  Changing this would resolve this issue without having to mess with how the nick command is implemented.
