### ISSUE TITLE
Snote when a remote server appears to be pinging out

### ISSUE THREAD

**Issue by examknow** [solanum-ircd/solanum#409]
Fire off a snote when a remote server has failed to provide a ping response after a certain threshold of time before it pings out. This would allow opers and any automated tooling to be aware of a laggy server that may be having issues before it splits off the network.

See also [UnrealIRCD implementation](https://github.com/unrealircd/unrealircd/blob/fd7a715e175c36f3db5271f706c493156a12b68b/src/ircd.c#L199-L209).

**Comment by dwfreed** [comment]
oftc-hybrid does this too, and it is handy. Place to implement it would be here: https://github.com/solanum-ircd/solanum/blob/fe83a335267c6226c2f4429035638f60e9e80b08/ircd/client.c#L370
