### ISSUE TITLE
authd crashes when handling new clients

### ISSUE THREAD

**Issue by hello-smile6** [solanum-ircd/solanum#435]
Something that changed this week has caused authd to crash in `SSL_do_handshake`every time a client connects, causing server notice spam and making the IRC server affected unusable.

**Comment by hello-smile6** [comment]
The issue only seems to occur with open proxy scanning enabled.

**Comment by dwfreed** [comment]
Please provide configs, logs, a backtrace, really anything useful.  You can see from the commit history yourself that there have been no recent changes to authd, so we can't even begin to guess what your issue is without more detail.

**Comment by dwfreed** [comment]
This issue can be reopened if you provide useful debugging information.
