### ISSUE TITLE
support more human friendly k/d/x-line duration format

### ISSUE THREAD

**Issue by jesopo** [solanum-ircd/solanum#85]
example:
`KLINE 11520 *@1.2.3.4 :go away`
could instead be:
`KLINE 1w1d *@1.2.3.4 :go away`

I think we'd want to support **w**eek, **d**ay, **h**our, **m**inute

I think this is where would want changing....
https://github.com/solanum-ircd/solanum/blob/6485005214c12ef94a50096e96478804b9cef556/ircd/s_newconf.c#L684-L685

**Comment by glguy** [comment]
This feels like the kind of thing people should be programming their clients to handle nicely; people shouldn't be manually quoting KLINE commands anyway.

The KLINE format is already a mess with optional duration and server parameters spread around.

I guess I buy the argument that this change doesn't hurt, so why not, but it feels like it's in the wrong place to me.

**Comment by dwfreed** [comment]
Fixed by #317
